sudo: false
language: node_js
node_js:
  - 4
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: "thiagogarbazza@gmail.com"
  api_key:
    secure: $NPM_AUTH_TOKEN
  on:
    tags: true
